server:
  port: 8084
  error:
    include-message: always

spring:
  application:
    name: inventory-service

otel:
  service:
    name: ${OTEL_SERVICE_NAME:inventory-service}
  instrumentation:
    spring-webmvc:
      enabled: ${OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED:true}
  traces:
    exporter: ${OTEL_TRACES_EXPORTER:logging}
  metrics:
    exporter: ${OTEL_METRICS_EXPORTER:none}
  logs:
    exporter: ${OTEL_LOGS_EXPORTER:none}
