server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: search-service

otel:
  service:
    name: search-service
  instrumentation:
    spring-webmvc:
      enabled: true
  traces:
    exporter: logging
  metrics:
    exporter: none
  logs:
    exporter: none
