server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: cart-service

search-service:
  base-url: http://localhost:8081

otel:
  service:
    name: ${OTEL_SERVICE_NAME:cart-service}
  instrumentation:
    spring-webmvc:
      enabled: ${OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED:true}
  traces:
    exporter: ${OTEL_TRACES_EXPORTER:logging}
  metrics:
    exporter: ${OTEL_METRICS_EXPORTER:none}
  logs:
    exporter: ${OTEL_LOGS_EXPORTER:none}
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
